# Generated by Django 5.2 on 2025-04-26 11:55

import django.contrib.postgres.indexes
import django.db.models.deletion
import events.models
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Event",
            fields=[
                (
                    "event_id",
                    models.UUIDField(
                        db_index=True,
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("title", models.CharField(max_length=200)),
                ("description", models.TextField()),
                ("image", models.ImageField(upload_to=events.models.get_image_path)),
                ("deadline", models.DateField()),
                (
                    "types_event",
                    models.CharField(
                        choices=[
                            ("grant", "Grant"),
                            ("internship", "Internship"),
                            ("event", "Event"),
                            ("olympiad", "Olympiad"),
                            ("course", "Course"),
                        ],
                        max_length=100,
                    ),
                ),
                ("type_url", models.URLField()),
                ("company", models.CharField(blank=True, max_length=100, null=True)),
                ("click", models.IntegerField(blank=True, default=0, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "verbose_name": "Event",
                "verbose_name_plural": "Events",
                "indexes": [
                    django.contrib.postgres.indexes.HashIndex(
                        fields=["event_id"], name="uuid_hash_index"
                    )
                ],
            },
        ),
        migrations.CreateModel(
            name="EventView",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("is_viewed", models.BooleanField(default=False)),
                ("is_liked", models.BooleanField(default=False)),
                ("is_linked", models.BooleanField(default=False)),
                (
                    "event",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="views",
                        to="events.event",
                    ),
                ),
            ],
        ),
    ]
